/**
 * Fallback demo plan returned when GOOGLE_API_KEY is absent.
 * Shape matches GeminiResponseSchema exactly — validated through the same
 * Zod parse path as real Gemini responses before being returned to the client.
 *
 * Scenario: 4-person team building a real-time collaborative task manager
 * in 48 hours.
 */
export const MOCK_GEMINI_RESPONSE = {
  summary:
    "Two parallel workstreams — Alice on frontend, Bob on backend — kick off simultaneously after a shared foundation phase, with Carol driving design and Dave owning all infrastructure. The 48-hour timeline is divided into five sequential phases: foundation, core development, integration, polish, and ship. The backend API contract established in Phase 1 is the single most critical dependency for unblocking both frontend and integration work.",

  phases: [
    {
      id: "phase-1",
      title: "Kickoff & Foundation",
      duration: "2h",
      startHour: 0,
      endHour: 2,
      assignees: ["Alice Chen", "Bob Rivera", "Carol Nguyen", "Dave Kim"],
      tasks: [
        {
          id: "task-1",
          title: "Monorepo scaffold, ESLint, Prettier, tsconfig",
          owner: "Dave Kim",
          dependencies: [],
          estimatedTime: "1h",
          tags: ["devops"],
          status: "pending",
        },
        {
          id: "task-2",
          title: "Design token system — palette, spacing, typography",
          owner: "Carol Nguyen",
          dependencies: [],
          estimatedTime: "1h",
          tags: ["design"],
          status: "pending",
        },
        {
          id: "task-3",
          title: "OpenAPI spec for core resources (users, tasks, projects)",
          owner: "Bob Rivera",
          dependencies: [],
          estimatedTime: "1h",
          tags: ["backend", "api"],
          status: "pending",
        },
        {
          id: "task-4",
          title: "React app bootstrap — Vite, routing, provider skeleton",
          owner: "Alice Chen",
          dependencies: [],
          estimatedTime: "1h",
          tags: ["frontend"],
          status: "pending",
        },
      ],
    },
    {
      id: "phase-2",
      title: "Core Development",
      duration: "14h",
      startHour: 2,
      endHour: 16,
      assignees: ["Alice Chen", "Bob Rivera", "Carol Nguyen", "Dave Kim"],
      tasks: [
        {
          id: "task-5",
          title: "PostgreSQL schema design and Prisma migrations",
          owner: "Bob Rivera",
          dependencies: ["task-3"],
          estimatedTime: "3h",
          tags: ["backend", "database"],
          status: "pending",
        },
        {
          id: "task-6",
          title: "Auth endpoints — register, login, JWT refresh",
          owner: "Bob Rivera",
          dependencies: ["task-5"],
          estimatedTime: "2.5h",
          tags: ["backend", "auth"],
          status: "pending",
        },
        {
          id: "task-7",
          title: "CRUD REST endpoints for tasks and projects",
          owner: "Bob Rivera",
          dependencies: ["task-5"],
          estimatedTime: "3h",
          tags: ["backend", "api"],
          status: "pending",
        },
        {
          id: "task-8",
          title: "WebSocket server for collaborative real-time editing",
          owner: "Bob Rivera",
          dependencies: ["task-7"],
          estimatedTime: "2h",
          tags: ["backend", "api"],
          status: "pending",
        },
        {
          id: "task-9",
          title: "Docker Compose with hot-reload dev environment",
          owner: "Dave Kim",
          dependencies: ["task-1"],
          estimatedTime: "2h",
          tags: ["devops", "infra"],
          status: "pending",
        },
        {
          id: "task-10",
          title: "Login, signup, and auth state management screens",
          owner: "Alice Chen",
          dependencies: ["task-4", "task-2"],
          estimatedTime: "2.5h",
          tags: ["frontend", "auth"],
          status: "pending",
        },
        {
          id: "task-11",
          title: "Project dashboard shell and navigation layout",
          owner: "Alice Chen",
          dependencies: ["task-4", "task-2"],
          estimatedTime: "3h",
          tags: ["frontend"],
          status: "pending",
        },
        {
          id: "task-12",
          title: "Drag-and-drop task cards with optimistic UI updates",
          owner: "Alice Chen",
          dependencies: ["task-11"],
          estimatedTime: "3h",
          tags: ["frontend"],
          status: "pending",
        },
        {
          id: "task-13",
          title: "High-fidelity mockups for dashboard, board, and detail views",
          owner: "Carol Nguyen",
          dependencies: ["task-2"],
          estimatedTime: "4h",
          tags: ["design"],
          status: "pending",
        },
        {
          id: "task-14",
          title: "Shared component library — buttons, inputs, modals, badges",
          owner: "Carol Nguyen",
          dependencies: ["task-13"],
          estimatedTime: "2.5h",
          tags: ["design", "frontend"],
          status: "pending",
        },
      ],
    },
    {
      id: "phase-3",
      title: "Integration",
      duration: "12h",
      startHour: 16,
      endHour: 28,
      assignees: ["Alice Chen", "Bob Rivera", "Carol Nguyen", "Dave Kim"],
      tasks: [
        {
          id: "task-15",
          title: "Wire React app to REST API — data fetching, error states",
          owner: "Alice Chen",
          dependencies: ["task-7", "task-11"],
          estimatedTime: "3h",
          tags: ["frontend", "integration"],
          status: "pending",
        },
        {
          id: "task-16",
          title: "WebSocket client hooks for real-time board updates",
          owner: "Alice Chen",
          dependencies: ["task-8", "task-12"],
          estimatedTime: "2h",
          tags: ["frontend", "integration"],
          status: "pending",
        },
        {
          id: "task-17",
          title: "Apply finalized design system across all screens",
          owner: "Carol Nguyen",
          dependencies: ["task-14", "task-11"],
          estimatedTime: "2.5h",
          tags: ["design", "frontend"],
          status: "pending",
        },
        {
          id: "task-18",
          title: "Integration tests and database query optimization",
          owner: "Bob Rivera",
          dependencies: ["task-7", "task-8"],
          estimatedTime: "2h",
          tags: ["backend", "testing"],
          status: "pending",
        },
        {
          id: "task-19",
          title: "GitHub Actions CI/CD pipeline to staging environment",
          owner: "Dave Kim",
          dependencies: ["task-9"],
          estimatedTime: "3h",
          tags: ["devops", "infra"],
          status: "pending",
        },
      ],
    },
    {
      id: "phase-4",
      title: "Polish",
      duration: "12h",
      startHour: 28,
      endHour: 40,
      assignees: ["Alice Chen", "Bob Rivera", "Carol Nguyen", "Dave Kim"],
      tasks: [
        {
          id: "task-20",
          title: "Responsive layout fixes and WCAG accessibility audit",
          owner: "Carol Nguyen",
          dependencies: ["task-17"],
          estimatedTime: "2h",
          tags: ["design", "frontend"],
          status: "pending",
        },
        {
          id: "task-21",
          title: "Playwright E2E tests for critical user flows",
          owner: "Alice Chen",
          dependencies: ["task-15", "task-16"],
          estimatedTime: "2h",
          tags: ["testing"],
          status: "pending",
        },
        {
          id: "task-22",
          title: "Production deployment to AWS ECS + RDS",
          owner: "Dave Kim",
          dependencies: ["task-19", "task-18"],
          estimatedTime: "2h",
          tags: ["devops", "infra"],
          status: "pending",
        },
        {
          id: "task-23",
          title: "Production smoke tests and incident response setup",
          owner: "Bob Rivera",
          dependencies: ["task-22"],
          estimatedTime: "1.5h",
          tags: ["backend", "testing"],
          status: "pending",
        },
      ],
    },
    {
      id: "phase-5",
      title: "Ship & Demo",
      duration: "8h",
      startHour: 40,
      endHour: 48,
      assignees: ["Alice Chen", "Bob Rivera", "Carol Nguyen", "Dave Kim"],
      tasks: [
        {
          id: "task-24",
          title: "Demo slide deck and live environment walkthrough script",
          owner: "Carol Nguyen",
          dependencies: ["task-20", "task-22"],
          estimatedTime: "1.5h",
          tags: ["docs"],
          status: "pending",
        },
        {
          id: "task-25",
          title: "Bug fixes surfaced from E2E and smoke tests",
          owner: "Alice Chen",
          dependencies: ["task-21"],
          estimatedTime: "1.5h",
          tags: ["frontend"],
          status: "pending",
        },
        {
          id: "task-26",
          title: "CloudWatch dashboards and alerting for prod",
          owner: "Dave Kim",
          dependencies: ["task-22"],
          estimatedTime: "1h",
          tags: ["devops", "infra"],
          status: "pending",
        },
        {
          id: "task-27",
          title: "API documentation and Postman collection export",
          owner: "Bob Rivera",
          dependencies: ["task-23"],
          estimatedTime: "1.5h",
          tags: ["backend", "docs"],
          status: "pending",
        },
      ],
    },
  ],

  bottlenecks: [
    {
      id: "bn-1",
      title: "Bob is sole backend engineer",
      description:
        "All seven backend tasks are owned by Bob. A blocker — illness, over-scoping, or a tricky bug — has no fallback and will cascade directly into Alice's integration work.",
      severity: "high",
      affectedTasks: ["task-15", "task-16", "task-18"],
    },
    {
      id: "bn-2",
      title: "REST API gates frontend integration",
      description:
        "Alice cannot begin wiring the React app (task-15) until task-7 is complete. If Bob's API development overruns, Alice's integration window shrinks and the Phase 3 deadline slips.",
      severity: "medium",
      affectedTasks: ["task-15", "task-21"],
    },
    {
      id: "bn-3",
      title: "Design delays cascade into polish phase",
      description:
        "Carol's high-fidelity designs (task-13) must land before the component library (task-14) and design system application (task-17). A 2h slip here pushes responsive fixes and demo prep into the final stretch.",
      severity: "medium",
      affectedTasks: ["task-17", "task-20", "task-24"],
    },
  ],

  suggestions: [
    {
      id: "sg-1",
      title: "Publish a mock API server on day one",
      body: "Generate a Prism or Mockoon server from the OpenAPI spec (task-3) immediately so Alice can develop against stable contracts without waiting for Bob's real endpoints. This decouples Phase 2 frontend and backend work entirely.",
      category: "workflow",
    },
    {
      id: "sg-2",
      title: "Consider replacing WebSockets with polling for v1",
      body: "Real-time WebSocket collaboration (task-8 + task-16) adds 4h of effort and introduces state-sync complexity. A 5-second polling fallback takes 30 minutes to implement and is far more robust under time pressure. Ship WebSockets as a stretch goal.",
      category: "scope",
    },
    {
      id: "sg-3",
      title: "Cross-train Dave as backup deployer",
      body: "Document the deployment runbook in a DEPLOY.md so Bob or Carol can trigger a production release if Dave is unavailable during the critical ship window. The single-engineer infra dependency is the highest operational risk.",
      category: "team",
    },
    {
      id: "sg-4",
      title: "Instrument observability before first feature deploy",
      body: "Dave should add structured logging and a /health endpoint during task-9 rather than retroactively in task-26. Early observability cuts debugging time significantly when integration issues surface in Phase 3.",
      category: "technical",
    },
  ],

  criticalPath: [
    {
      taskId: "task-3",
      taskTitle: "OpenAPI spec for core resources",
      phase: "Phase 1: Kickoff & Foundation",
      reason: "Unblocks all backend work; Bob cannot start the database schema without an agreed contract.",
    },
    {
      taskId: "task-5",
      taskTitle: "PostgreSQL schema and Prisma migrations",
      phase: "Phase 2: Core Development",
      reason: "Foundation for every API endpoint; task-6, task-7, and task-8 all depend on it.",
    },
    {
      taskId: "task-7",
      taskTitle: "CRUD REST endpoints for tasks and projects",
      phase: "Phase 2: Core Development",
      reason: "Directly gates Alice's integration work (task-15) and Bob's integration tests (task-18).",
    },
    {
      taskId: "task-8",
      taskTitle: "WebSocket server for real-time editing",
      phase: "Phase 2: Core Development",
      reason: "Required before Alice can implement the real-time sync client (task-16).",
    },
    {
      taskId: "task-16",
      taskTitle: "WebSocket client hooks for real-time board updates",
      phase: "Phase 3: Integration",
      reason: "The real-time feature is a key demo differentiator; delays here push E2E tests (task-21) out of scope.",
    },
    {
      taskId: "task-21",
      taskTitle: "Playwright E2E tests for critical user flows",
      phase: "Phase 4: Polish",
      reason: "Final quality gate before production deployment; failures here require rework that eats into demo prep time.",
    },
  ],

  overloadWarnings: [
    {
      person: "Alice Chen",
      allocatedHours: 17.5,
      maxHours: 15,
      message:
        "Alice has 17% more work than the recommended 15h ceiling. Consider moving the E2E test suite (task-21, 2h) to Bob after integration tests complete.",
    },
    {
      person: "Bob Rivera",
      allocatedHours: 16.5,
      maxHours: 15,
      message:
        "Bob owns all backend tasks including the critical path. At 16.5h allocated he has little buffer. Dropping API documentation (task-27) to post-hackathon saves 1.5h.",
    },
  ],
};
